import {
  app,
  BrowserWindow,
  Menu,
  ipcMain,
  shell,
  globalShortcut,
} from "electron";
import { setupWebSocketHandlers } from "./setup/websocketHandler";
import { setupApiHandler } from "./setup/apiHandler";
import { setupAutoUpdater } from "./setup/autoUpdater";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      webSecurity: true,
    },
    frame: true,
    autoHideMenuBar: true,
  });

  // Set Content Security Policy to allow WebSocket connections
  mainWindow.webContents.session.webRequest.onHeadersReceived(
    (details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            "default-src 'self' 'unsafe-inline' data:; connect-src 'self' wss://www.pathofexile.com https://www.pathofexile.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://web.poecdn.com;",
          ],
        },
      });
    }
  );

  // Create context menu for right-click inspect
  const contextMenu = Menu.buildFromTemplate([
    {
      label: "Inspect Element",
      click: () => {
        mainWindow.webContents.openDevTools();
      },
    },
    {
      label: "Toggle DevTools",
      click: () => {
        mainWindow.webContents.toggleDevTools();
      },
    },
  ]);

  // Set up right-click context menu
  mainWindow.webContents.on("context-menu", () => {
    contextMenu.popup();
  });

  Menu.setApplicationMenu(null);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // Comment this out for production
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();

  setupWebSocketHandlers();
  setupApiHandler();
  setupAutoUpdater();

  // Register global shortcuts for DevTools
  globalShortcut.register("CommandOrControl+Shift+I", () => {
    mainWindow.webContents.toggleDevTools();
  });

  globalShortcut.register("F12", () => {
    mainWindow.webContents.toggleDevTools();
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Clean up global shortcuts when the app is about to quit
app.on("will-quit", () => {
  globalShortcut.unregisterAll();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// Add this with your other ipcMain handlers
ipcMain.handle("shell-open-external", async (_, url) => {
  if (
    typeof url === "string" &&
    (url.startsWith("https://") || url.startsWith("http://"))
  ) {
    await shell.openExternal(url);
    return true;
  }
  return false;
});
