import {
  app,
  BrowserWindow,
  Menu,
  ipcMain,
  shell,
  globalShortcut,
  screen,
} from "electron";
import path from "path";

import {
  initializeOverlayWindow,
  showOverlayWindow,
  hideOverlayWindow,
  updateOverlayPosition,
  destroyOverlayWindow,
} from "./overlay/gridOverlay";

import { initializeHandlers, initializeStorage } from "./setup/initialize";
import { persistentStore } from "../shared/store/sharedStore";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 900,
    width: 1400,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      webSecurity: true,
    },
    frame: true,
    autoHideMenuBar: true,
    show: true,
    icon: path.join(__dirname, "../renderer/assets/icon.ico"),
  });

  // Set Content Security Policy to allow WebSocket connections
  mainWindow.webContents.session.webRequest.onHeadersReceived(
    (details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            "default-src 'self' 'unsafe-inline' data:; connect-src 'self' wss://www.pathofexile.com https://www.pathofexile.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://web.poecdn.com;",
          ],
        },
      });
    }
  );

  // Create context menu for right-click inspect
  const contextMenu = Menu.buildFromTemplate([
    {
      label: "Inspect Element",
      click: () => {
        mainWindow.webContents.openDevTools();
      },
    },
    {
      label: "Toggle DevTools",
      click: () => {
        mainWindow.webContents.toggleDevTools();
      },
    },
  ]);

  // Set up right-click context menu
  mainWindow.webContents.on("context-menu", (event, params) => {
    contextMenu.popup({
      window: mainWindow,
      x: params.x,
      y: params.y,
    });
  });

  Menu.setApplicationMenu(null);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Show window when ready to prevent visual flash
  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
  });

  // Handle window closed
  mainWindow.on("closed", () => {
    console.log("Main window closed, cleaning up grid overlay...");
    destroyOverlayWindow();
    mainWindow = null as any;
  });

  // Handle web contents errors
  mainWindow.webContents.on(
    "did-fail-load",
    (event, errorCode, errorDescription, validatedURL) => {
      console.error(
        "Failed to load:",
        errorCode,
        errorDescription,
        validatedURL
      );
    }
  );

  // Open the DevTools.
  // Comment this out for production
  if (process.env.NODE_ENV === "development")
    mainWindow.webContents.openDevTools();

  // Temporary: Always open DevTools for debugging
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();

  initializeStorage();
  initializeHandlers();

  // Initialize grid overlay window
  const gridConfig = persistentStore.getState().gridConfig;
  initializeOverlayWindow(gridConfig);
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {

  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Cleanup when app is about to quit
app.on("before-quit", () => {
  console.log("App is about to quit, cleaning up grid overlay...");
});

// Clean up global shortcuts when the app is about to quit
app.on("will-quit", () => {
  console.log("App will quit, final cleanup of grid overlay...");
  destroyOverlayWindow();
  globalShortcut.unregisterAll();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// Add this with your other ipcMain handlers
ipcMain.handle("shell-open-external", async (_, url) => {
  if (
    typeof url === "string" &&
    (url.startsWith("https://") || url.startsWith("http://"))
  ) {
    await shell.openExternal(url);
    return true;
  }
  return false;
});

// Screen API handlers
ipcMain.handle("get-displays", async () => {
  const displays = screen.getAllDisplays();
  return displays.map((display, index) => ({
    id: index,
    label: display.label || `Display ${index + 1}`,
    bounds: display.bounds,
  }));
});

// Grid overlay handlers
ipcMain.handle(
  "show-grid-overlay",
  async (_, highlightX = 0, highlightY = 0) => {
    showOverlayWindow(highlightX, highlightY);
    return true;
  }
);

ipcMain.handle("hide-grid-overlay", async () => {
  console.log("hide-grid-overlay IPC handler called");
  hideOverlayWindow();
  return true;
});

ipcMain.handle("update-grid-position", async (_, config) => {
  updateOverlayPosition(config);
  return true;
});
